apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-db-svc
spec:
  selector:
    app: tech-challenge-db-deployment
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30200