apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-challenge-db-pv
  labels:
    app: tech-challenge-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/guilherme/Documents/pessoal/tech-challenge-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube