apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-challenge-db-pvc
  labels:
    app: tech-challenge-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 800Mi