apiVersion: apps/v1
kind: Deployment
metadata:
  name:  tech-challenge-app-deployment
  labels:
    app:  tech-challenge-app-deployment
spec:
  selector:
    matchLabels:
      app: tech-challenge-app-deployment
  template:
    metadata:
      labels:
        app:  tech-challenge-app-deployment
    spec:
      containers:
        - name: tech-challenge-app-container
          image: gcamargo1997/goc-tech-challenge-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MARIADB_URL
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-app-config-map
                  key: MARIADB_URL
            - name: SWAGGER_URL
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-app-config-map
                  key: SWAGGER_URL
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-db-user-secret
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-db-password-secret
                  key: MARIADB_PASSWORD
          resources:
            requests:
              cpu: "250m"
              memory: "950Mi"
            limits:
              cpu: "500m"
              memory: "2500Mi"
          livenessProbe:
            httpGet:
              path: /tech-challenge/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3