name: 'Pipeline'
on:
  pull_request:
    branches:
      - 'develop'
      - 'release'
      - 'main'
permissions:
  pull-requests: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      JACOCO_COVERAGE_OVERALL: 50
      JACOCO_COVERAGE_CHANGED_FILES: 80
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Run tests
        run: ./gradlew clean test jacocoTestReport
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: ${{env.JACOCO_COVERAGE_OVERALL}}
          min-coverage-changed-files: ${{env.JACOCO_COVERAGE_CHANGED_FILES}}
          title: ':lobster: Coverage Report'

      - run: echo "Expected overall coverage ${{env.JACOCO_COVERAGE_OVERALL}}. Jacoco Coverage ${{ steps.jacoco.outputs.coverage-overall }}"
      - run: echo "Expected changed files coverage ${{env.JACOCO_COVERAGE_CHANGED_FILES}}. Jacoco Coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      - name: Fail Overall Coverage
        if: steps.jacoco.outputs.coverage-overall < 50
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Overall Coverage less than required!')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '![](https://i.gifer.com/origin/fb/fbecb86c26733a655325b3bef320069a_w200.gif)\n\nFaltou teste nesse projeto ai'
            })
      - name: Fail Changed Files Coverage
        if: steps.jacoco.outputs.coverage-changed-files < 80
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Changed Files Coverage less than required!')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '![](https://i.gifer.com/origin/fb/fbecb86c26733a655325b3bef320069a_w200.gif)\n\nFaltou teste nesses arquivos ai'
            })