name: 'Pipeline'
on:
  pull_request:
    branches:
      - 'develop'
      - 'release'
      - 'main'
#  pull_request:
#    branches:
#      - 'develop'
#      - 'release'
#      - 'main'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Run tests
        run: ./gradlew clean test
  build-image:
    runs-on: ubuntu-latest
    needs: run-tests
    env:
      BRANCH_NAME: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Create Docker Tag
        run: |
          if [[ ${{env.BRANCH_NAME == 'main'}} ]]; then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${{env.BRANCH_NAME}}-latest"
          fi
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/goc-tech-challenge-api:${{ env.DOCKER_TAG }}